// Code generated by protoc-gen-go. DO NOT EDIT.
// source: useraction.proto

/*
Package beacontower is a generated protocol buffer package.

It is generated from these files:
	useraction.proto

It has these top-level messages:
	UserAction
*/
package beacontower

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 承载用户行为的消息
type UserAction struct {
	AppId     string `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Action    string `protobuf:"bytes,3,opt,name=action" json:"action,omitempty"`
	Timestamp int64  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *UserAction) Reset()                    { *m = UserAction{} }
func (m *UserAction) String() string            { return proto.CompactTextString(m) }
func (*UserAction) ProtoMessage()               {}
func (*UserAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserAction) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *UserAction) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserAction) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UserAction) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*UserAction)(nil), "beacontower.UserAction")
}

func init() { proto.RegisterFile("useraction.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x2d, 0x4e, 0x2d,
	0x4a, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0x4a,
	0x4d, 0x4c, 0xce, 0xcf, 0x2b, 0xc9, 0x2f, 0x4f, 0x2d, 0x52, 0x2a, 0xe2, 0xe2, 0x0a, 0x2d, 0x4e,
	0x2d, 0x72, 0x04, 0x2b, 0x10, 0x12, 0xe5, 0x62, 0x4b, 0x2c, 0x28, 0x88, 0xcf, 0x4c, 0x91, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x4d, 0x2c, 0x28, 0xf0, 0x4c, 0x11, 0x12, 0xe7, 0x62, 0x07,
	0x99, 0x02, 0x12, 0x67, 0x02, 0x8b, 0xb3, 0x81, 0xb8, 0x9e, 0x29, 0x42, 0x62, 0x5c, 0x6c, 0x10,
	0xa3, 0x25, 0x98, 0x21, 0xe2, 0x10, 0x9e, 0x90, 0x0c, 0x17, 0x67, 0x49, 0x66, 0x6e, 0x6a, 0x71,
	0x49, 0x62, 0x6e, 0x81, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x42, 0x20, 0x89, 0x0d, 0xec,
	0x0e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xda, 0xaa, 0x66, 0xa7, 0x9b, 0x00, 0x00, 0x00,
}
