// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

/*
Package ucenter is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	SearchRequest
	RawMessage
	DirectMessage
	BroadcaseMessage
*/
package ucenter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Query         string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	PageNumber    int32  `protobuf:"varint,2,opt,name=page_number,json=pageNumber" json:"page_number,omitempty"`
	ResultPerPage int32  `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage" json:"result_per_page,omitempty"`
	Res           string `protobuf:"bytes,4,opt,name=res" json:"res,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *SearchRequest) GetRes() string {
	if m != nil {
		return m.Res
	}
	return ""
}

type RawMessage struct {
	Version   int32  `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	MsgId     string `protobuf:"bytes,2,opt,name=msgId" json:"msgId,omitempty"`
	MsgType   string `protobuf:"bytes,3,opt,name=msgType" json:"msgType,omitempty"`
	Timestamp int32  `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Payload   string `protobuf:"bytes,5,opt,name=payload" json:"payload,omitempty"`
}

func (m *RawMessage) Reset()                    { *m = RawMessage{} }
func (m *RawMessage) String() string            { return proto.CompactTextString(m) }
func (*RawMessage) ProtoMessage()               {}
func (*RawMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RawMessage) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *RawMessage) GetMsgId() string {
	if m != nil {
		return m.MsgId
	}
	return ""
}

func (m *RawMessage) GetMsgType() string {
	if m != nil {
		return m.MsgType
	}
	return ""
}

func (m *RawMessage) GetTimestamp() int32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RawMessage) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type DirectMessage struct {
	AppId        string      `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppKey       string      `protobuf:"bytes,2,opt,name=app_key,json=appKey" json:"app_key,omitempty"`
	AppSecret    string      `protobuf:"bytes,3,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	FromAccount  string      `protobuf:"bytes,4,opt,name=fromAccount" json:"fromAccount,omitempty"`
	FromResource string      `protobuf:"bytes,5,opt,name=fromResource" json:"fromResource,omitempty"`
	Msg          *RawMessage `protobuf:"bytes,6,opt,name=msg" json:"msg,omitempty"`
}

func (m *DirectMessage) Reset()                    { *m = DirectMessage{} }
func (m *DirectMessage) String() string            { return proto.CompactTextString(m) }
func (*DirectMessage) ProtoMessage()               {}
func (*DirectMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DirectMessage) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DirectMessage) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *DirectMessage) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

func (m *DirectMessage) GetFromAccount() string {
	if m != nil {
		return m.FromAccount
	}
	return ""
}

func (m *DirectMessage) GetFromResource() string {
	if m != nil {
		return m.FromResource
	}
	return ""
}

func (m *DirectMessage) GetMsg() *RawMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

type BroadcaseMessage struct {
	AppId        string      `protobuf:"bytes,1,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AppKey       string      `protobuf:"bytes,2,opt,name=app_key,json=appKey" json:"app_key,omitempty"`
	AppSecret    string      `protobuf:"bytes,3,opt,name=app_secret,json=appSecret" json:"app_secret,omitempty"`
	FromAccount  string      `protobuf:"bytes,4,opt,name=fromAccount" json:"fromAccount,omitempty"`
	FromResource string      `protobuf:"bytes,5,opt,name=fromResource" json:"fromResource,omitempty"`
	Msg          *RawMessage `protobuf:"bytes,6,opt,name=msg" json:"msg,omitempty"`
}

func (m *BroadcaseMessage) Reset()                    { *m = BroadcaseMessage{} }
func (m *BroadcaseMessage) String() string            { return proto.CompactTextString(m) }
func (*BroadcaseMessage) ProtoMessage()               {}
func (*BroadcaseMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BroadcaseMessage) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *BroadcaseMessage) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *BroadcaseMessage) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

func (m *BroadcaseMessage) GetFromAccount() string {
	if m != nil {
		return m.FromAccount
	}
	return ""
}

func (m *BroadcaseMessage) GetFromResource() string {
	if m != nil {
		return m.FromResource
	}
	return ""
}

func (m *BroadcaseMessage) GetMsg() *RawMessage {
	if m != nil {
		return m.Msg
	}
	return nil
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "ucenter.SearchRequest")
	proto.RegisterType((*RawMessage)(nil), "ucenter.RawMessage")
	proto.RegisterType((*DirectMessage)(nil), "ucenter.DirectMessage")
	proto.RegisterType((*BroadcaseMessage)(nil), "ucenter.BroadcaseMessage")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x92, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0xe5, 0xbf, 0x7f, 0x5a, 0x65, 0x4a, 0x45, 0x65, 0x40, 0x64, 0x01, 0x22, 0x8a, 0x04,
	0xea, 0xaa, 0x0b, 0x38, 0x01, 0x88, 0x4d, 0x85, 0x40, 0x95, 0xcb, 0x3e, 0x72, 0x9d, 0x21, 0x44,
	0x34, 0xb1, 0x6b, 0x3b, 0xa0, 0xec, 0x38, 0x01, 0x17, 0x43, 0xe2, 0x4c, 0xc8, 0x4e, 0xa2, 0xc2,
	0x15, 0xd8, 0xe5, 0x7d, 0xf3, 0x26, 0xf3, 0x3c, 0x36, 0x80, 0x45, 0x63, 0xe7, 0x4a, 0x4b, 0x2b,
	0xe9, 0xa8, 0x16, 0x58, 0x59, 0xd4, 0xc9, 0x3b, 0x81, 0xc9, 0x0a, 0xb9, 0x16, 0xcf, 0x0c, 0xb7,
	0x35, 0x1a, 0x4b, 0x0f, 0x21, 0xd8, 0xd6, 0xa8, 0x9b, 0x88, 0xc4, 0x64, 0x16, 0xb2, 0x56, 0xd0,
	0x33, 0x18, 0x2b, 0x9e, 0x63, 0x5a, 0xd5, 0xe5, 0x1a, 0x75, 0xf4, 0x2f, 0x26, 0xb3, 0x80, 0x81,
	0x43, 0x0f, 0x9e, 0xd0, 0x0b, 0xd8, 0xd7, 0x68, 0xea, 0x8d, 0x4d, 0x15, 0xea, 0xd4, 0x15, 0xa2,
	0x81, 0x37, 0x4d, 0x5a, 0xbc, 0x44, 0xbd, 0xe4, 0x39, 0xd2, 0x29, 0x0c, 0x34, 0x9a, 0xe8, 0xbf,
	0xff, 0xb9, 0xfb, 0x4c, 0x3e, 0x08, 0x00, 0xe3, 0x6f, 0xf7, 0x68, 0x8c, 0x33, 0x44, 0x30, 0x7a,
	0x45, 0x6d, 0x0a, 0x59, 0xf9, 0x04, 0x01, 0xeb, 0xa5, 0x4b, 0x56, 0x9a, 0x7c, 0x91, 0xf9, 0xe9,
	0x21, 0x6b, 0x85, 0xf3, 0x97, 0x26, 0x7f, 0x6c, 0x54, 0x3b, 0x30, 0x64, 0xbd, 0xa4, 0x27, 0x10,
	0xda, 0xa2, 0x44, 0x63, 0x79, 0xa9, 0xfc, 0xc0, 0x80, 0xed, 0x80, 0xeb, 0x53, 0xbc, 0xd9, 0x48,
	0x9e, 0x45, 0x41, 0xdb, 0xd7, 0xc9, 0xe4, 0x93, 0xc0, 0xe4, 0xb6, 0xd0, 0x28, 0x6c, 0x9f, 0xe9,
	0x08, 0x86, 0x5c, 0xa9, 0xb4, 0xc8, 0xfa, 0xa5, 0x70, 0xa5, 0x16, 0x19, 0x3d, 0x86, 0x91, 0xc3,
	0x2f, 0xd8, 0x74, 0x91, 0x9c, 0xeb, 0x0e, 0x1b, 0x7a, 0x0a, 0xe0, 0x0a, 0x06, 0x85, 0x46, 0xdb,
	0xc5, 0x0a, 0xb9, 0x52, 0x2b, 0x0f, 0x68, 0x0c, 0xe3, 0x27, 0x2d, 0xcb, 0x6b, 0x21, 0x64, 0x5d,
	0xd9, 0x6e, 0x17, 0x3f, 0x11, 0x4d, 0x60, 0xcf, 0x49, 0x86, 0x46, 0xd6, 0x5a, 0x60, 0x97, 0xf0,
	0x17, 0xa3, 0xe7, 0x30, 0x28, 0x4d, 0x1e, 0x0d, 0x63, 0x32, 0x1b, 0x5f, 0x1e, 0xcc, 0xbb, 0x1b,
	0x9d, 0xef, 0x56, 0xc9, 0x5c, 0x3d, 0xf9, 0x22, 0x30, 0xbd, 0xd1, 0x92, 0x67, 0x82, 0x1b, 0xfc,
	0x03, 0x07, 0x5a, 0x0f, 0xfd, 0x13, 0xbe, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x64, 0xec, 0x6e,
	0xc7, 0xd0, 0x02, 0x00, 0x00,
}
